spring:
  datasource-test:
#    maridb jdbc
#    driverClassName: org.mariadb.jdbc.Driver
#    jdbc-url: jdbc:mariadb://localhost:3306/test
#    username: greatwall
#    password: stqin@1992

#    postgres jdbc
    driverClassName: org.postgresql.Driver
    jdbc-url: jdbc:postgresql://localhost:5432/testDB
    username: postgres
    password: stqin@1992

#    mysql jdbc
#    driverClassName: com.mysql.jdbc.Driver
#    jdbc-url: jdbc:mysql://mysql.sqlpub.com:3306/test_mysqldb
#    username: stqin01
#    password: d4YYDTSCxzthZcDu

#    hikari:
#      minimum-idle: 5
#      idle-timeout: 180000
#      maximum-pool-size: 10
#      auto-commit: true
#      max-lifetime: 1800000
#      connection-timeout: 30000
scheduler:
  corePoolSize: 2
  maxPoolSize: 6
